#! /bin/bash

#This ensures that the current github org gets imprinted into global-functions get_github_org
source ../ports.info
sed "s/__GITHUB_ORG__/${GITHUB_ORG}/g" < ./global-functions > pkg/global-functions

cp ./gamecontrollerdb.txt pkg/