#! /bin/bash
set -e

apt-get update

apt-get install -y libsdl2-image-dev \
                   libsdl2-mixer-dev \
                   gettext \
                   libphysfs-dev \
                   libsdl2-ttf-dev \
                   libboost-program-options-dev