#!/bin/bash
set -e

# Current directory of the script
DIR="$(realpath $( dirname "${BASH_SOURCE[0]}" ))"

source "${DIR}/global-functions"

ESUDO=$(get_sudo)
$ESUDO rm -rf ~/.local/share/blockattack
ln -sfv $DIR/ ~/.local/share

export LD_LIBRARY_PATH="$DIR/libs"

SDL_GAMECONTROLLERCONFIG="$(get_sdl_controls)"
export SDL_GAMECONTROLLERCONFIG

launch_with_oga_controls blockattack
